---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-controller
  namespace: tinypaas-core
spec:
  selector:
    matchLabels:
      name: image-controller
  template:
    metadata:
      labels:
        name: image-controller
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: image-controller
      securityContext:
        runAsNonRoot: true
      containers:
      - name: image-controller
        image: eirini/tinypaas-image-controller
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 100m
            memory: 200Mi
